# @package _global_

xp_name: 4DVarNet-SSH-SST
params:
  flag_update_training_config: false
  sst_model: nolinear-tanh-bn
  k_n_grad: 3
  n_grad: 5
  apha_grad_descent_step: 0.
  learn_fsgd_param: false
  dT: 7
  DimAE: 50
  dim_obs_sst_feat: 20
  dim_grad_solver: 150
  phi_param: unet1
  ckpt_name: 4DVarNet-SSH-SST-{epoch:02d}-{val_loss:.4f}
  use_sst_obs: true
  use_sst_state: false
  patch_weight:
    _target_: lit_model_uv.get_cropped_hanning_mask
    patch_size: ${datamodule.slice_win}
    crop:
      time: 1
  val_diag_freq: 5
  padding_mode: 'reflect'
  residual_wrt_geo_velocities: 0
  type_div_train_loss: 1
  alpha_mse_ssh: 50.
  alpha_mse_gssh: 1000.
  alpha_mse_uv: 50.
  alpha_mse_uv_geo: 25.
  alpha_mse_div: 1000.
  alpha_mse_strain: 0.
  sig_filter_div: 1.
  norm_obs: l2
  norm_prior: l2
  sampling_model: sampling-from-sst
  nb_feat_sampling_operator: 0
  alpha_sampling_uv: 10.
  thr_l1_sampling_uv: 0.1
datamodule:
  aug_train_data: true
  resize_factor: 1
defaults:
  - /xp/ronan/base_xp_uv
  - /splits/dc_boost_swot@datamodule
  - /xp/xp_aug/aug/with_aug_state_uv
#  - /xp/xp_aug/aug/with_mm_aug_state_uv
  - /xp/xp_aug/dl/d240_p240x5_s240x1
  - /xp/xp_aug/sst/with_sst
  - /xp/xp_aug/loss/map
  - /xp/xp_aug/train_strat/const_lr_ngrad_5_3cas
  - _self_
