# @package _global_
params:
  ckpt_name: 'modelSLAInterpGF-Exp3-{epoch:02d}-{val_loss:.2f}'
  norm_obs: 'l2'
  norm_prior: 'l2'

lit_mod_cls: lit_model.LitModel

datamodule:
  _target_: dataloading.FourDVarNetDataModule
  slice_win:
    lat: 200
    lon: 200
    time: 5
  strides:
    lat: 200
    lon: 200
    time: 1
  train_slices: 
    - _target_: builtins.slice
      _args_: ['2012-10-01', '2012-11-20']
    - _target_: builtins.slice
      _args_: ['2013-02-07', '2013-09-30']
  test_slices: 
    - _target_: builtins.slice
      _args_: ['2013-01-03', '2013-01-27']
  val_slices: 
    - _target_: builtins.slice
      _args_: ['2012-11-30', '2012-12-24']
  oi_path: ${file_paths.oi_swot_4nadir}
  oi_var: ssh_mod
  obs_mask_path: ${file_paths.pseudo_obs}
  obs_mask_var: ssh_mod
  gt_path: ${file_paths.natl_ssh}
  gt_var: ssh
  resolution: 1/20
  dl_kwargs:
    batch_size: 2
    num_workers: 2


